name: CI

on:
  pull_request:
    types: [ "opened", "synchronize", "edited", "reopened" ]
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday
  workflow_dispatch:
    inputs: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  ci-checks:
    name: "Tests"
    runs-on: "${{ matrix.operating-system }}"

    services:
      postgres:
        image: postgres:15.10
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
          POSTGRES_DB: ci_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ci_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mysql:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: ci_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="bash -c 'echo > /dev/tcp/127.0.0.1/3306'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    if: |
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    strategy:
      matrix:
        operating-system: [ "ubuntu-latest" ]
        php-version: ["8.1", "8.2", "8.3", "8.4"]

    steps:
      - name: Wait for MariaDB
        run: |
          for i in {1..30}; do
            if mysql -h mysql -uroot -proot -e "SELECT 1"; then
              echo "MariaDB is ready"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            if PGPASSWORD=ci_password psql -h postgres -U ci_user -d ci_db -c "SELECT 1"; then
              echo "Postgres is ready"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: "composer:v2"

      - name: Verify PHP version
        run: php -v

      - name: Create directories
        run: mkdir -p src temp log

      - name: "Composer"
        uses: "ulovdomov/github-actions/.github/actions/php-composer@v3.0.0"

      - name: Run code sniffer
        run: composer run cs

      - name: Run PhpStan
        run: composer run phpstan

      - name: Run tests
        run: composer run tests

      - name: "Upload Artifacts"
        if: failure()
        uses: "ulovdomov/github-actions/.github/actions/upload-artifacts@v2"
        with:
          log-dir: "./log"